baseURL = "https://dakotahpena.studio/"
languageCode = "en-us"
title = "Dakotah Peña"
sectionPagesMenu = "main"
publishDir = "public"
copyright = "© Dakotah Peña"
enableGitInfo = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[author]
name = "Dakotah"
email = "hey@dakotahpena.studio"

[params]
author = "Dakotah"
contactEmail = "hey@dakotahpena.studio"
dateFormat = "Jan 2, 2006"
description = "Dakotah Peña, maker."
images = ["site-feature-image.jpg"]
analyticsId = "56b72f90-ebf6-4dea-b795-83a5e9fdb5e6"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
category = "categories"
tag = "tags"
