name: Lint
on: [push]
jobs:
  run-linters:
    name: Lint TOML config file
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@v1.5.5

      - name: TOML linter
        run: tombi lint config.toml config.development.toml
